Edit Developer Guide Glossary
AY2223S1-CS2103T-W11-3/tp pull request #15
Opened 2022-09-27 15:12 UTC by nvmdava

2022-09-27 18:15 UTC, chloeelim reviewed
Hm, not very sure about this- but deleting customer should also delete their commission to prevent orphaning, so should the deletion of all commissions tied to the customer also be in the MSS?

2022-09-27 18:15 UTC, chloeelim commented on docs/DeveloperGuide.md
> +4.  ArtBuddy deletes the customer
```suggestion
4.  ArtBuddy warns the user that all commissions under the customer will be deleted, and confirms whether the user still wants to proceed
5.  User confirms.
6.  ArtBuddy deletes the customer
```

2022-09-27 18:15 UTC, chloeelim commented on docs/DeveloperGuide.md
```suggestion

* 4a. The user chooses not to proceed with the deletion.

  Use case ends.

```

2022-09-28 05:07 UTC, nvmdava commented
Yeah, I think that works, thanks for the suggestion.

2022-09-29 08:12 UTC, chloeelim reviewed
The definitions for the glossary seem too 'circular', if they are self explanatory I think they shouldn't be in the glossary. In particular, I think `commission` could be explained in simpler terms because non-artsy people (ie: most developers) might not be familiar with a `commission` in context of arts.

2022-09-29 08:12 UTC, chloeelim commented on docs/DeveloperGuide.md
> +* **Iteration**: A single iteration of the commission, contains an image for the commission and a text comment on the image.
```suggestion
* **Customer**: A contact detail. Contains information about the customer, and a list of commissions.
* **Commission**: An art piece requested by a customer. Contains specifics about the commission and list of iterations.
* **Iteration**: A single version of a commission. Contains an image and a text comment on the image. 
```

2022-09-29 16:23 UTC, ngxingyu requested changes
some minor grammar fixes, I'm fine with the rest of it.

2022-09-29 16:23 UTC, ngxingyu commented on docs/DeveloperGuide.md
> +* **Commission**: An art piece requested by a customer that has been delivered or under progress. Contains specifics about the commission and list of iterations.
```suggestion
* **Commission**: An art piece requested by a customer that has been delivered or is in progress. Contains specifics about the commission and a list of iterations.
```

2022-09-29 16:23 UTC, ngxingyu commented on docs/DeveloperGuide.md
> +4.  ArtBuddy shows the list of commissions the customer made and the detail of the customer
```suggestion
4.  ArtBuddy shows the list of commissions the customer made and the details of the customer
```

2022-09-29 16:49 UTC, ngxingyu approved these changes

2022-09-29 16:56 UTC, merged