Edit User Guide: opencus, delcus
AY2223S1-CS2103T-W11-3/tp pull request #62
Opened 2022-09-29 17:29 UTC by nvmdava

2022-09-29 23:50 UTC, seelengxd requested changes
LGTM - minor nit to fix.

2022-09-29 23:50 UTC, seelengxd commented on docs/UserGuide.md
> +
```suggestion
```

Should this extra newline be removed?

2022-09-30 04:14 UTC, seelengxd requested changes
LGTM (almost) - can we use `customer` for consistency? :P

2022-09-30 04:14 UTC, seelengxd commented on docs/UserGuide.md
> +* The index refers to the index number shown in the displayed person list.
```suggestion
* The index refers to the index number shown in the displayed customer list.
```

2022-09-30 04:14 UTC, seelengxd commented on docs/UserGuide.md
> +  Deletes the 2nd person in the ArtBuddy and all commissions made by the person.
```suggestion
  Deletes the 2nd person in the ArtBuddy and all commissions made by the customer.
```

2022-09-30 04:14 UTC, seelengxd commented on docs/UserGuide.md
>  * The index refers to the index number shown in the displayed person list.
```suggestion
* Deletes the customer at the specified `INDEX`.
* The index refers to the index number shown in the displayed customer list.
```

2022-09-30 07:05 UTC, nvmdava commented
True, thanks for noticing

2022-09-30 07:11 UTC, seelengxd approved these changes

2022-09-30 07:14 UTC, merged