Logic: add opencom command
AY2223S1-CS2103T-W11-3/tp pull request #91
Opened 2022-10-11 09:53 UTC by seelengxd

2022-10-12 10:55 UTC, chloeelim requested changes
LGTM (almost), just some very minor styling issues to address.

2022-10-12 10:55 UTC, chloeelim commented on src/main/java/seedu/address/logic/parser/OpenCommissionCommandParser.java
> + * Parses input arguments and creates a new OpenCommissionCommand object
Missing punctuation at the end of the Javadoc header?

2022-10-12 10:55 UTC, chloeelim commented on src/main/java/seedu/address/logic/parser/OpenCommissionCommandParser.java
> +     * @throws ParseException if the user input does not conform the expected format
Missing punctuation at the end of the JavaDoc here as well I believe?

2022-10-12 10:55 UTC, chloeelim commented on src/main/java/seedu/address/logic/commands/OpenCommissionCommand.java
> +            + ": Opens a commission and shows commission details"
The phrasing here is a little weird, perhaps we should try to make this clearer?

2022-10-13 06:22 UTC, zlimez approved these changes
LGTM

2022-10-13 07:10 UTC, chloeelim approved these changes

2022-10-13 07:21 UTC, merged